version: '3.8'

services:
  shell:
    build: ./mf-shell
    ports:
      - "3000:3000"
    networks:
      - mf-network

  characters:
    build: ./mf-characters
    ports:
      - "3001:3001"
    networks:
      - mf-network

  detail:
    build: ./mf-character-detail
    ports:
      - "3002:3002"
    networks:
      - mf-network

networks:
  mf-network:
    driver: bridge
